--create table Employee_Details(EmployeeID serial,FirstName varchar(50),LastName varchar(50),Email varchar(100),PhoneNumber varchar(15),HireDate date,	Salary decimal,	DepartmentID int,	IsActive boolean,	
--JobTitle varchar)
insert into Employee_Details values(1,'Avantika','Ramteke','avantikaramteke@gmail.com',98898976787,'22-06-2023',50000,2,'yes','Data Analyst'),
(2,'Khushi','Roy','khushiroy@gmail.com',9867856587,'02-12-2024',40000,3,'yes','Developer'),
(3,'Avani','Meshram','avaniroy@gmail.com',9865787787,'11-07-2023',30000,4,'yes','Engineer'),
(4,'Aishwarya','Warthe','aishwaryawarthe@gmail.com',9870564532,'29-07-2024',20000,5,'yes','Manager'),
(5,'Anjali','Tirpude','anjalitirpude@gmail.com',9098765487,'01-10-2024',10000,6,'yes','Teacher')